### ISSUE TITLE
Fix automated testing

### ISSUE THREAD

**Issue by ProgramFOX** [ProgramFOX/Chess.NET#10]
It broke after the update to .NET Standard.

**Comment by MisinformedDNA** [comment]
I'm trying to keep the issues isolated, but in fixing #19, I ran into the issue that NUnit does not support .NET Standard 1.3, but it does support 1.4. If targeting 1.4 is OK, I should be able to fix this issue.

**Comment by ProgramFOX** [comment]
Yes, that's alright.

**Comment by MisinformedDNA** [comment]
Didn't need to upgrade, so still on .NET Standard 1.3. 👍

**Comment by ProgramFOX** [comment]
Still fails, I think I'll have to make major changes to circle.yml before it actually works again.

**Comment by ProgramFOX** [comment]
There are some strange errors on `sudo apt-get update` on the CI, I'll take the rest of this issue on me.

**Comment by MisinformedDNA** [comment]
OK. I was getting the live unit testing to work in VS. To run tests at the command line, I just used:

`dotnet test .\ChessDotNet.Variants.Tests\ChessDotNet.Variants.Tests.csproj`

NOTE: `dotnet test .\ChessDotNet.Variants.Tests\bin\Debug\ChessDotNet.Variants.Tests.dll` did not work for me
```

**Comment by ProgramFOX** [comment]
Finally got it working! I had to change the test projects from .NET Framework 4.5 to .NET Core, get rid of the signing with the .snk files, and add several commands to make sure that apt-get update and dotnet restore work. Works again now: https://circleci.com/gh/ProgramFOX/Chess.NET/161
