### ISSUE TITLE
Board json serialization/deserialization...

### ISSUE THREAD

**Issue by nvrnight** [ProgramFOX/Chess.NET#14]
It would be nice to be able to easily serialize/deserialize the game board, currently chokes up on the King piece because of not having an eligible constructor using Newtonsoft.Json.

**Comment by polytomous** [comment]
@nvrnight How interested would you be in writing that functionality? I'm not interested in writing this fix (not relevant to my interests) but I can help you with that if you'd like. (Code review and pair programming are the best things I can offer.) I'm not the maintainer but I've been spending a lot of time in this code for another project.

**Comment by nvrnight** [comment]
If there's someone around to review/merge a pull request I could probably put in the time to do it.

**Comment by nvrnight** [comment]
I'm unfortunately struggling to get .NET Core 1.x stuff building, I'm on 2.0. I've downloaded the 1.x SDK and am trying to see if I can switch my version to it some how. I think once I get the thing to compile everything else will be a cakewalk. I've already got an idea of what needs to be changed.

**Comment by nvrnight** [comment]
I just migrated the code to use .NET Core SDK 2.0 rather than fiddling with it. I don't think there should be any compatibility issues with the changes needed to be made, incoming pull request shortly.
