### ISSUE TITLE
Use non-preview project files while continuing to target .NET Standard 1.3

### ISSUE THREAD

**Issue by MisinformedDNA** [ProgramFOX/Chess.NET#19]
This library is currently targeting a pre-release version of .NET Core. Libraries should actually target .NET Standard anyway. v1 of .NET Standard was missing a bunch of features, so must libraries target 2.0.

**Comment by ProgramFOX** [comment]
I'm targetting .NET Standard 1.3, not .NET Core. When I ported this to .NET Standard, I picked the lowest possible version that still worked to ensure compatibility with as many users as possible. Does targetting 1.3 break it for 2.0? If not, is there still a reason to switch?

**Comment by MisinformedDNA** [comment]
No, 1.3 would be fine. But according to your csproj file, you are targeting .NET 5.0, which doesn't exist. Microsoft also deprecated the project.json file.
