### ISSUE TITLE
NullReferenceException thrown for invalid movement

### ISSUE THREAD

**Issue by MisinformedDNA** [ProgramFOX/Chess.NET#21]
The following code is trying to move a piece that doesn't exist. There should certainly be an error, but a NullReferenceException makes it seem like the code is broken.

```csharp
var game = new ChessGame();
game.MakeMove(new Move("a3", "a4", Player.White), true);
```

> System.NullReferenceException
>   HResult=0x80004003
>   Message=Object reference not set to an instance of an object.
>   Source=ChessDotNet
>   StackTrace:
>    at ChessDotNet.ChessGame.GetSanForMove(Move move, Piece movingPiece, Boolean isCapture, CastlingType castle, List`1 ambiguities)
>    at ChessDotNet.ChessGame.MakeMove(Move move, Boolean alreadyValidated, Piece& captured)
>    at ChessDotNet.ChessGame.MakeMove(Move move, Boolean alreadyValidated)
>

**Comment by ProgramFOX** [comment]
Perhaps this is badly documented, but this is the expected behavior. The 'true' parameter is the `alreadyValidated` parameter, which basically tells Chess.NET that it can safely assume that the move is validated and correct. If you pass 'false' instead, it will return MoveType.Invalid.

I'm closing this for now, but let me know if this is bad practice.

**Comment by MisinformedDNA** [comment]
Yep, throwing `NullReferenceException` is bad practice. I would throw something more appropriate like an `InvalidOperationException`. with a message like "Move could not be executed" or "Source piece does not exist".

I did read the documentation of `alreadyValidated` but I assumed that would allow me to make moves like a2 to h8; moves that are "possible", but not _valid_. Whereas a4 to a5 would simply be impossible.

**Comment by MisinformedDNA** [comment]
See https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/using-standard-exception-types#nullreferenceexception-indexoutofrangeexception-and-accessviolationexception

**Comment by ProgramFOX** [comment]
That's fair. Reopening. I guess the steps to take are: 1) Figuring out what exceptions can all be thrown on invalid moves. 2) Preventing them and throw an InvalidOperationException.

**Comment by kirakosyan** [comment]
similar issue in Atomic
https://github.com/ProgramFOX/Chess.NET/pull/27
